services:
  # Backend API
  - type: web
    name: planora-backend
    runtime: node
    region: frankfurt # or oregon, singapore
    plan: free # or starter ($7/month)
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
    healthCheckPath: /api/health

  # Frontend (optional - you can use Vercel instead)
  - type: web
    name: planora-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: planora-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # PostgreSQL Database (free tier available)
  - name: planora-db
    databaseName: planora
    plan: free
    region: frankfurt
    user: planora
